unitreeのメールに星座占いを追加
tkmtnt7000/jsk_robot pull request #1
Opened 2022-05-16 16:20 UTC by MiyabiTane

@tkmtnt7000 
スパーキーのメールに星座占いを追加してみました。お時間ある時に試してみてほしいです。実行に`pip install emoji`が必要です

関数での動作は確認済みですが、このスクリプトはすぐ手元で動かせず動作確認できていないのでエラー等吐いたらお知らせください。お手数おかけして申し訳ないです...。
よろしくお願いします

https://github.com/k-okada/jsk_robot/pull/24

2022-05-16 23:28 UTC, tkmtnt7000 commented
<img src="https://user-images.githubusercontent.com/67531577/168698226-dd7b1eb6-153b-43e1-b911-944c6df7c1e2.jpg" width=70%>

2022-05-16 23:29 UTC, tkmtnt7000 commented
めっちゃいい感じですね！

2022-05-16 23:38 UTC, tkmtnt7000 requested changes

2022-05-16 23:38 UTC, tkmtnt7000 commented on jsk_unitree_robot/jsk_unitree_startup/scripts/launch-email.py
> +           　 8: ":scream:", 9: ":heart_eyes:", 10: ":wink:", 11: ":sleepy:", 12: ":sweat:"}
全角スペースが入っているような気がします

2022-05-16 23:38 UTC, tkmtnt7000 commented on jsk_unitree_robot/jsk_unitree_startup/scripts/launch-email.py
> +            response.close()
この部分はpython2系でも動く気がするのでインデントを一つ上げてelseから出しておいても良いかと思いました．

2022-05-17 05:20 UTC, MiyabiTane commented
早速のご対応ありがとうございます！
直したのでご確認お願いします

`api_key_file = '/var/lib/robot/openweathermap_api_key.txt'`
このファイルが手元になかったので関連事項をコメントアウトしてデバッグしました

2022-05-17 12:55 UTC, tkmtnt7000 approved these changes

2022-05-17 12:56 UTC, merged